### ISSUE TITLE
Client Name and Service in Bookings List have broken links

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-ui#12]
## Symptom
On booking list page, clicking on the client's name or on the service's name navigates to `#` instead of the real location.

## Steps to reproduce
- Go to the bookings page and create a new booking (it will appear in the table of all bookings). 
- Click on the service name. 
- Observe symptom.

## Reason
During development, there were just `#` placeholders on that links. Now we have real data.

## Solution
Use client's and service's links with ID placeholder from the backend and put ID parameter to appropriate place there.

**Comment by XedinUnknown** [comment]
Waiting to merge #13.
