### ISSUE TITLE
UI Fixes on Bookings List/Calendar pages

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-ui#28]
### Problem
Styles on Bookings List/Calendar pages are not great and should be updated.

### Solution
1. In calendar month view, change `.rc-calendar--booking .rc-event-field--title` to have `font-weight: 600;`.
2. Change `.fc-unthemed td.fc-today` to have  `background-color: #B2D7FF;`.
3. Set `.rc-calendar .fc-today .fc-day-number` to have `font-size: 14px;`.
4. Add `background-color: #f9f9f9;` to `.rc-calendar .fc-past`.

**Comment by markzahra** [comment]
Solution number 2 has not been changed. The background is still yellow, not blue.

**Comment by romalytvynenko** [comment]
Leaving today's cell color unchanged for now, because in full calendar blue color is used for highlighting selected days and yellow is for current day.
