### ISSUE TITLE
Initial list of available statuses keys is wrong 

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-ui#38]
### Problem 
Initial list of available statuses keys is not filtered correctly, which produces incorrect behavior on client.

### Bugs because of this
1. The "All" filter for the Bookings list does not show all bookings. Rather, it remains blank until I click on a status filter.

If I visit "Scheduled", which has two bookings, the list will show both. If I go back to "All", it will now show the two scheduled bookings, but not any bookings with any other status.

2. When I am on the Bookings List view and I add a new booking manually, the Nedit booking modal closes, the status filters show one booking increasing for the status I selected, but the list does not update to show the booking I just created.

3. Screen options changes are applied when I hit the Apply button, but once I refresh the page, the screen options changes I made are not saved, and all statuses are selected again.

### Steps to reproduce
- Create some `in_cart` bookings via wizard
- Go to bookings page, observe bug 1.
- Create booking via editor, observe bug 2.
- Open screen options change it, press save.
- Refresh page, open screen options again, observe bug 3.

### Reason
Initial list of available statuses keys is not filtered correctly.

### Solution
Filter statuses keys correctly.

**Comment by markzahra** [comment]
I cannot yet test issue number 2 in Alpha 11 due to the unrelated bug causing the available sessions to not be shown in the Nedit Booking modal. I will test again in Alpha 12.
