### ISSUE TITLE
Improve download's nedit page's UX for beta users

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-ui#41]
### Problem
We have known limitations of application, but we are not notifying users about them.

### Solution
In order to provide better UX during beta 1 we should display this messages on download's new/edit page.

1. Disable "day" and "week" options in the Session Lengths tab for the Nedit Download page.

	Add a notice at the top of the tab to explain that "Day" and "Week" durations are coming soon. It should use the same styling as the notice on the Availability tab. 	Text to use:

	> The "day" and "week" durations for session lengths are coming soon.

2. Hide option on "Display Options" tab of Nedit Download page. 

	Replace option text with text saying:

	> "Dates and times are shown to the customer using their browser's timezone, both during the booking process and at checkout. Soon, this will be optional."

3. Add a limit to the session length.

	The limit must be of 23 hours 59 minutes.

**Comment by markzahra** [comment]
In relation to 1 above, @romalytvynenko the user can still set the session length to 24 hours to achieve one day, and so on. Is it worth limiting the entry field to 23 for hours and 59 for minutes?

If it is a hassle for Beta1, we must trust users not to do that. If they do, they can use it but the bug will be present. I have no trouble with that as we already say it's under development.
