### ISSUE TITLE
Screen options show statuses wrongly

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/rcmod-wp-bookings-ui#5]
“Booking Statuses to display in calendar” in screen options of the Bookings page is showing statuses that should not be displayed there, such as "Cart". It is also showing all as unchecked.

- The list of statuses should be filtered to exclude those from a blacklist. That list should come from a single source of truth (the state), which should come from the server.
- The ones that are allowed to be displayed should all be checked by default.

**Comment by XedinUnknown** [comment]
@romalytvynenko, FYI I improved the description, which includes some important points now.
